// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/Bernardo-Txa/printlab/web/components"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<section id=\"inicio\" class=\"hero-section\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div class=\"grid min-h-[calc(100vh-4rem)] items-center gap-10 py-14 sm:py-18 lg:grid-cols-[1.05fr_0.95fr] lg:py-20\"><div class=\"max-w-3xl\"><p class=\"brand-kicker\">Impressao 3D sob medida</p><h1 class=\"mt-5 text-balance text-4xl font-semibold text-foreground sm:text-5xl lg:text-6xl\">Ideias impressas com precisao, cor e criterio.</h1><p class=\"mt-6 max-w-2xl text-pretty text-lg leading-8 text-muted\">A PrintLab une fabricacao digital e experimentacao para transformar conceitos em objetos bem definidos, com uma base online preparada para crescer com seguranca.</p><div class=\"mt-8 flex flex-col gap-3 sm:flex-row\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = components.LinkButton("#contato", "Falar sobre uma ideia").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = components.LinkButtonSecondary("#como-funciona", "Entender o processo").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</div></div><div class=\"hero-visual\" aria-label=\"Identidade visual da PrintLab\"><div class=\"hero-brand-card\"><img class=\"hero-logo-image\" src=\"/static/images/branding/logo-printlab-primary.png\" width=\"1448\" height=\"1086\" alt=\"Logo da PrintLab com impressora 3D e frasco de laboratorio\"><div class=\"brand-dot brand-dot-blue\"></div><div class=\"brand-dot brand-dot-pink\"></div><div class=\"brand-dot brand-dot-teal\"></div><div class=\"brand-dot brand-dot-yellow\"></div><div class=\"brand-layer-stack\" aria-hidden=\"true\"><span class=\"brand-layer brand-layer-blue\"></span> <span class=\"brand-layer brand-layer-teal\"></span> <span class=\"brand-layer brand-layer-pink\"></span> <span class=\"brand-layer brand-layer-yellow\"></span></div></div></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = components.Container().Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"mt-10 grid gap-4 md:grid-cols-3\"><div class=\"info-card\"><h3 class=\"text-lg font-semibold text-foreground\">Clareza</h3><p class=\"mt-3 text-sm leading-6 text-muted\">Conteudo direto para explicar possibilidades, materiais e proximos passos sem excesso de promessa.</p></div><div class=\"info-card\"><h3 class=\"text-lg font-semibold text-foreground\">Seguranca</h3><p class=\"mt-3 text-sm leading-6 text-muted\">A arquitetura mantem regras sensiveis no backend e evita depender do navegador para decisoes importantes.</p></div><div class=\"info-card\"><h3 class=\"text-lg font-semibold text-foreground\">Evolucao</h3><p class=\"mt-3 text-sm leading-6 text-muted\">Layout, componentes e tokens visuais foram alinhados a marca para receber catalogo e fluxos futuros.</p></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = components.Section("sobre", "Proposta", "Uma base visual para fabricacao digital.", "A PrintLab combina impressao 3D, criterio tecnico e uma linguagem acessivel. Esta versao organiza a presenca digital sem antecipar funcionalidades comerciais que ainda serao desenvolvidas.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var5 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div class=\"mt-10 grid gap-4 lg:grid-cols-3\"><div class=\"process-card\"><span class=\"step-number\">01</span><h3 class=\"mt-5 text-lg font-semibold text-foreground\">Entendimento</h3><p class=\"mt-3 text-sm leading-6 text-muted\">Coleta das necessidades do projeto e dos criterios que vao orientar a producao.</p></div><div class=\"process-card\"><span class=\"step-number\">02</span><h3 class=\"mt-5 text-lg font-semibold text-foreground\">Preparacao</h3><p class=\"mt-3 text-sm leading-6 text-muted\">Avaliacao de materiais, geometria e parametros de impressao quando a funcionalidade for implementada.</p></div><div class=\"process-card\"><span class=\"step-number\">03</span><h3 class=\"mt-5 text-lg font-semibold text-foreground\">Producao</h3><p class=\"mt-3 text-sm leading-6 text-muted\">Execucao e acompanhamento deverao aparecer em fases futuras, depois das regras de pedido.</p></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = components.Section("como-funciona", "Como funciona", "Da ideia ao objeto, com etapas transparentes.", "O fluxo comercial completo ainda sera definido nas proximas fases. Por enquanto, esta area apresenta a direcao visual para explicar o processo futuramente.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var5), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<div class=\"mt-10\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = components.EmptyState("Catalogo em preparacao", "Os produtos serao exibidos aqui quando o cadastro, o banco de dados e as regras de publicacao estiverem aprovados.").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = components.Section("produtos", "Catalogo futuro", "Espaco preparado para produtos da PrintLab.", "A listagem real sera implementada somente depois da fase de banco e catalogo. Nenhum produto, preco ou estoque esta publicado nesta versao.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, " <section id=\"contato\" class=\"section-block bg-foreground text-primary-foreground\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Var7 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"grid gap-8 py-16 md:grid-cols-[1fr_auto] md:items-center\"><div><p class=\"text-sm font-semibold uppercase tracking-normal text-secondary-light\">Contato</p><h2 class=\"mt-3 text-balance text-3xl font-semibold sm:text-4xl\">Tem uma ideia para imprimir?</h2><p class=\"mt-4 max-w-2xl text-pretty text-base leading-7 text-primary-foreground/80\">Esta area sera conectada a um canal oficial quando o fluxo de atendimento for definido. Por enquanto, ela marca o espaco de contato da homepage.</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = components.LinkButtonSecondary("#inicio", "Voltar ao inicio").Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return nil
			})
			templ_7745c5c3_Err = components.Container().Render(templ.WithChildren(ctx, templ_7745c5c3_Var7), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</section>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = components.Layout("PrintLab | Impressao 3D", "Impressao 3D feita para transformar ideias em objetos.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
